[package]
name = "teddy"
version = "2.1.0"
authors = ["jdcoffre <jeandenis.coffre@sonarsource.com>",
            "drautureau <david.rautureau@sonarsource.com>",
            "hgomez <henri.gomez@sonarsource.com",
            "francois.teychene@gmail.com"]
edition = "2021"

[dependencies]
actix-web = "0.7"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
failure = "0.1"
log = "0.4"
simple_logger = "5.0"
futures = "0.1"
base64 = "0.22"
